### ISSUE TITLE
opusscript_native._free is not a function

### ISSUE THREAD

**Issue by Emtecsus** [manuel-rw/jellyfin-discord-music-bot#214]
**Describe the bug**
ERROR [DiscordVoiceService] TypeError: opusscript_native._free is not a function

**To Reproduce**
1.Start the bot
2.Play any song
3.Disconnect the bot 
4.Play another song and the bot will enter the chat but no sound is produced

LOG
      
yarn run v1.22.15
$ node dist/main
(node:28) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [NestFactory] Starting Nest application...
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] AppModule dependencies initialized +39ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] DiscordModule dependencies initialized +1ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] PlaybackModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] ServeStaticModule dependencies initialized +1ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +50ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] DiscordHostModule dependencies initialized +2ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] UpdatesModule dependencies initialized +1ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] JellyfinClientModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] DiscordModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] DiscordModule dependencies initialized +1ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] HealthModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] DiscordClientModule dependencies initialized +1ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [InstanceLoader] CommandModule dependencies initialized +0ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [RoutesResolver] HealthController {/health}: +19ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [RouterExplorer] Mapped {/health, GET} route +2ms
[Nest] 28  - 08/06/2023, 11:06:00 PM     LOG [PlayItemCommand] Subscribe to event(on): interactionCreate
(node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 interactionCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit
[Nest] 28  - 08/06/2023, 11:06:01 PM     LOG [NestApplication] Nest application successfully started +688ms
[Nest] 28  - 08/06/2023, 11:06:42 PM     LOG [RegisterCommandService] All global commands are registered!
[Nest] 28  - 08/06/2023, 11:09:37 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:12:05 PM   ERROR [DiscordVoiceService] TypeError: opusscript_native._free is not a function
[Nest] 28  - 08/06/2023, 11:12:05 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:12:33 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:14:53 PM   ERROR [DiscordVoiceService] TypeError: opusscript_native._free is not a function
[Nest] 28  - 08/06/2023, 11:14:54 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:16:00 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:17:35 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:18:06 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged
[Nest] 28  - 08/06/2023, 11:20:43 PM   ERROR [DiscordVoiceService] TypeError: opusscript_native._free is not a function
[Nest] 28  - 08/06/2023, 11:20:43 PM    WARN [JellyfinWebSocketService] Received a package from the socket of unknown type: UserDataChanged

**Comment by manuel-rw** [comment]
Thanks for the issue. I'll try to reproduce.

**Comment by sssionek** [comment]
Hi, this seems to stem from https://github.com/abalabahaha/opusscript/issues/24.
There is a fix ready for this - https://github.com/abalabahaha/opusscript/pull/23, I have been unable to test it, but can you try pulling it in as a dependency in the test branch?

**Comment by Emtecsus** [comment]
> Hi, this seems to stem from [abalabahaha/opusscript#24](https://github.com/abalabahaha/opusscript/issues/24). There is a fix ready for this - [abalabahaha/opusscript#23](https://github.com/abalabahaha/opusscript/pull/23), I have been unable to test it, but can you try pulling it in as a dependency in the test branch?

I'm not really sure how to do it, but i'll give it a try

**Comment by manuel-rw** [comment]
Hi, sorry for my late reply on this topic. As long as https://github.com/abalabahaha/opusscript/pull/23 doesn't get merged, I'm afraid that I can't build a test image with the bug fix. Copying the source files directly is often janky. @abalabahaha can you help us out?

**Comment by sssionek** [comment]
@manuel-rw abalabahaha updated opusscript a few hours ago, could you try now?

**Comment by manuel-rw** [comment]
Done. Github auto-closed the issue. Please let me know if it works now

**Comment by sssionek** [comment]
> Any update @sssionek ?

Yeah, I'm still having issues with crashes but they seem like a completely different issue - reported as #238.
The opusscript message is gone and looking through my logs, it seems that before that other crash - playback setup works as expected.
```
[Nest] 28  - 10/14/2023, 7:23:30 PM   DEBUG [JellyfinWebSocketService] Opening WebSocket with client id jellyfin-discord-bot...
[Nest] 28  - 10/14/2023, 7:23:30 PM   DEBUG [PlayItemCommand] Extracted 1 tracks from the search item
[Nest] 28  - 10/14/2023, 7:23:30 PM   DEBUG [PlayItemCommand] Adding 1 tracks with a duration of 267833.472 ticks
[Nest] 28  - 10/14/2023, 7:23:30 PM   DEBUG [JellyinPlaystateService] Reporting playback start on track 'xxx'
[Nest] 28  - 10/14/2023, 7:23:30 PM   DEBUG [JellyfinStreamBuilderService] Building stream for 'xxx' with bitrate 96000
[Nest] 28  - 10/14/2023, 7:23:31 PM   DEBUG [DiscordVoiceService] Playing audio resource with volume 1
[Nest] 28  - 10/14/2023, 7:23:31 PM   DEBUG [DiscordVoiceService] Initialized new instance of AudioPlayer because it has not been defined yet
[Nest] 28  - 10/14/2023, 7:23:31 PM   DEBUG [DiscordVoiceService] Audio player changed state from idle to buffering
[Nest] 28  - 10/14/2023, 7:23:31 PM VERBOSE [DiscordVoiceService] Reporting progress: 0 on track 4d78c6084308de2c8de5b7e32a58c434
[Nest] 28  - 10/14/2023, 7:23:31 PM     LOG [RegisterCommandService] All global commands are registered!
[Nest] 28  - 10/14/2023, 7:23:31 PM   DEBUG [DiscordVoiceService] Audio player changed state from buffering to playing
```
Thank you for getting this fix in, while it doesn't solve the issue fully for me, it's at least a step closer ;)
